-- Create a separate table for tracking daily habits
create table if not exists public.habit_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    date date not null,
    habits jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, date)
);

-- RLS Policies
alter table public.habit_logs enable row level security;

create policy "Users can view their own habit logs"
    on public.habit_logs for select
    using (auth.uid() = user_id);

create policy "Users can insert their own habit logs"
    on public.habit_logs for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own habit logs"
    on public.habit_logs for update
    using (auth.uid() = user_id);

-- Index for performance
create index habit_logs_user_date_idx on public.habit_logs (user_id, date);
